### ISSUE TITLE
[BUG] Going into expose crashes the UI in Ubuntu 26.04

### ISSUE THREAD

**Issue by bmonjoie** [G-dH/vertical-workspaces#308]
**Describe the bug**
Pressing the super key to go into expose crashes the UI. The top bar is still working, but the rest is not responding to click events.

**To Reproduce**
1.  Start your session with the extension enabled
2. Press on the "Super" key to go into expose.
3. The UI is not responding anymore.

**Expected behavior**
The expose mode is correctly displayed, and the UI responds to click events.

**System:**
 - OS: Ubuntu 26.04
 - Version of V-Shell extension: 50.0/109
 - Source of installation: extension.gnome.org

**System log output**
```
Extension vertical-workspaces@G-dH.github.com: TypeError: this.setGridModes is not a function
```

**Fix**
After searching for this code in the repository, I have found that some changes were made to add a safe call operator (`?`). 

**For people with the same problem,** you need to edit `~/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js`

line 200:
```
_appDisplay._grid.setGridModes?.();
```

line 1411:
```
this.setGridModes?.([
            {
                columns: 20,
                rows: 20,
            },
        ]);
```
Then, log out, and log back in.

**For the maintainer,** would it be possible to publish a new version with this fix?

Thank you

**Comment by G-dH** [comment]
You can install V-Shell directly from this repository. However, the _appDisplay_ module doesn't work in Ubuntu 26.04, so you can disable it instead (_Settings > Modules > appDisplay_).

**Comment by bmonjoie** [comment]
Thank you for releasing the fix 🙂
